INSERT INTO `user_groups`(`name`, `selectable`) VALUES
('admin', 0),
('tanár', 1),
('diák', 1)

INSERT INTO `subjects`(`subject`) VALUES
('Biológia-egészségtan'),
('Dráma és tánc'),
('Ének-zene'),
('Erkölcstan'),
('Erkölcstan/hittan'),
('Etika'),
('Filozófia'),
('Fizika'),
('Földrajz'),
('Hon- és népismeret'),
('Informatika'),
('Kémia'),
('Kommunikáció – magyar nyelv és irodalom'),
('Környezetismeret'),
('Latin örökségünk'),
('Magyar nyelv és irodalom'),
('Matematika'),
('Mozgóképkultúra és médiaismeret'),
('Művészetek'),
('Tánc és mozgás'),
('Társadalmi, állampolgári és gazdasági ismeretek'),
('Társadalmi, állampolgári és gazdasági ismeretek – 5-6. évfolyam'),
('Társadalomismeret'),
('Technika, életvitel és gyakorlat'),
('Természetismeret'),
('Természettudományi gyakorlatok'),
('Testnevelés és sport'),
('Történelem, társadalmi és állampolgári ismeretek'),
('Vizuális kultúra')

INSERT INTO `subjects`(`subject`) VALUES
('albán'),
('angol'),
('cseh'),
('dán'),
('észt'),
('finn'),
('francia'),
('görög'),
('grúz'),
('héber'),
('hindi'),
('holland'),
('horvát'),
('indonéz'),
('ír'),
('izlandi'),
('japán'),
('jávai'),
('katalán'),
('kazah'),
('kínai'),
('latin'),
('lengyel'),
('lett'),
('litván'),
('luxemburgi'),
('macedón'),
('maláj'),
('máltai'),
('mongol'),
('német'),
('nepáli'),
('norvég'),
('olasz'),
('orosz'),
('örmény'),
('pandzsábi'),
('pastu'),
('perzsa'),
('portugál'),
('román'),
('skót-gael'),
('spanyol'),
('svéd'),
('szanszkrit'),
('szerb'),
('szlovák'),
('szlovén'),
('thai'),
('török'),
('ukrán'),
('urdu'),
('üzbég'),
('vietnami'),
('walesi')

INSERT INTO `grades`(`grade`) VALUES
('Általános iskola (1-4. évfolyam)'),
('Általános iskola (5-8. évfolyam)'),
('Gimnázium (négyosztályos)'),
('Gimnázium (hatosztályos)'),
('Gimnázium (nyolcosztályos)'),
('Szakközépiskolák'),
('Szakiskolák'),
('Idegen nyelv'),
('Felsőoktatás')